name: Release Helm Charts
on:
 push:
   branches:
     - main
jobs:
 release:
   runs-on: default-runner
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
 
     - name: Configure Git
       run: |
         git config user.name "$GITHUB_ACTOR"
         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

     - name: Install Helm
       uses: azure/setup-helm@v1
       with:
         version: v3.5.2

     - name: Install helm plugin on S3 bucket
       run: |
         helm plugin install https://github.com/hypnoglow/helm-s3.git
         
     # Configure AWS credentials.
     - name: AWS Credentials
       id: aws-credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} 
         role-duration-seconds: 900 
         aws-region: us-east-1 
         role-skip-session-tagging: true
         
     - name: Upload Helm chart to S3 bucket
       run: | 
         helm s3 push ./path/to/chart.tgz my-s3-bucket/path/to/chart.tgz

